"""check

Revision ID: b8f625dd32c5
Revises: 5d1ce1fee886
Create Date: 2026-03-02 22:24:19.921406

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b8f625dd32c5'
down_revision: str | Sequence[str] | None = '5d1ce1fee886'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_roles_id'), table_name='company_roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_roles_id'), 'company_roles', ['id'], unique=False)
    # ### end Alembic commands ###
