"""add company_sectors table

Revision ID: 39273f2c8079
Revises: b8f625dd32c5
Create Date: 2026-03-03 18:35:33.664206

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39273f2c8079'
down_revision: str | Sequence[str] | None = 'b8f625dd32c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('nace_code', sa.String(length=20), nullable=False),
    sa.Column('nace_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'nace_code', name='uq_company_sector_company_nace')
    )
    op.create_index(op.f('ix_company_sectors_company_id'), 'company_sectors', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sectors_id'), 'company_sectors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_sectors_id'), table_name='company_sectors')
    op.drop_index(op.f('ix_company_sectors_company_id'), table_name='company_sectors')
    op.drop_table('company_sectors')
    # ### end Alembic commands ###
