"""make password_hash nullable, expand company fields, add company_brands and company_sector_profiles tables

Revision ID: bc94816f00a3
Revises: b6ff38a53930
Create Date: 2026-03-22 19:25:11.086467

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bc94816f00a3'
down_revision: str | Sequence[str] | None = 'b6ff38a53930'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mersis_number', sa.String(length=50), nullable=False),
    sa.Column('tax_number', sa.String(length=20), nullable=False),
    sa.Column('tax_office', sa.String(length=100), nullable=False),
    sa.Column('foundation_date', sa.Date(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('headquarters_address', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('iban_try', sa.String(length=34), nullable=True),
    sa.Column('sgk_debt', sa.Boolean(), nullable=True),
    sa.Column('tax_debt', sa.Boolean(), nullable=True),
    sa.Column('service_export_last_year_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('foreign_income_last_year_usd', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('nace_code', sa.String(length=20), nullable=True),
    sa.Column('activity_sectors', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('exporter_unions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('hib_member_no', sa.String(length=100), nullable=True),
    sa.Column('contact_full_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('kep_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_mersis_number'), 'companies', ['mersis_number'], unique=False)
    op.create_index(op.f('ix_companies_tax_number'), 'companies', ['tax_number'], unique=False)
    op.create_table('company_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('company_brands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('has_domestic_registration', sa.Boolean(), nullable=False),
    sa.Column('has_international_registration', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'brand_name', name='uq_company_brand_name')
    )
    op.create_index(op.f('ix_company_brands_company_id'), 'company_brands', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_brands_id'), 'company_brands', ['id'], unique=False)
    op.create_table('company_sector_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('sector_type', sa.String(length=50), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('value_text', sa.String(length=1000), nullable=True),
    sa.Column('value_numeric', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'field_key', name='uq_company_sector_profile_field')
    )
    op.create_index(op.f('ix_company_sector_profiles_company_id'), 'company_sector_profiles', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sector_profiles_id'), 'company_sector_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_company_sector_profiles_sector_type'), 'company_sector_profiles', ['sector_type'], unique=False)
    op.create_table('company_sectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('nace_code', sa.String(length=20), nullable=False),
    sa.Column('nace_name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'nace_code', name='uq_company_sector_company_nace')
    )
    op.create_index(op.f('ix_company_sectors_company_id'), 'company_sectors', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_sectors_id'), 'company_sectors', ['id'], unique=False)
    op.create_table('users_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['company_roles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_users_companies_user_company')
    )
    op.create_index(op.f('ix_users_companies_company_id'), 'users_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_companies_id'), 'users_companies', ['id'], unique=False)
    op.create_index(op.f('ix_users_companies_is_active'), 'users_companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_companies_user_id'), 'users_companies', ['user_id'], unique=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_users_companies_user_id'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_is_active'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_id'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_company_id'), table_name='users_companies')
    op.drop_table('users_companies')
    op.drop_index(op.f('ix_company_sectors_id'), table_name='company_sectors')
    op.drop_index(op.f('ix_company_sectors_company_id'), table_name='company_sectors')
    op.drop_table('company_sectors')
    op.drop_index(op.f('ix_company_sector_profiles_sector_type'), table_name='company_sector_profiles')
    op.drop_index(op.f('ix_company_sector_profiles_id'), table_name='company_sector_profiles')
    op.drop_index(op.f('ix_company_sector_profiles_company_id'), table_name='company_sector_profiles')
    op.drop_table('company_sector_profiles')
    op.drop_index(op.f('ix_company_brands_id'), table_name='company_brands')
    op.drop_index(op.f('ix_company_brands_company_id'), table_name='company_brands')
    op.drop_table('company_brands')
    op.drop_table('company_roles')
    op.drop_index(op.f('ix_companies_tax_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_mersis_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
