"""add users_companies table

Revision ID: fde4df0b6f54
Revises: 6593b6f85039
Create Date: 2026-03-02 20:44:08.142624

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fde4df0b6f54'
down_revision: str | Sequence[str] | None = '375042d7d902'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column(
    'is_active',
    sa.Boolean(),
    server_default=sa.text('true'),
    nullable=False
),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uq_users_companies_user_company')
    )
    op.create_index(op.f('ix_users_companies_company_id'), 'users_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_companies_id'), 'users_companies', ['id'], unique=False)
    op.create_index(op.f('ix_users_companies_is_active'), 'users_companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_companies_user_id'), 'users_companies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_companies_user_id'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_is_active'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_id'), table_name='users_companies')
    op.drop_index(op.f('ix_users_companies_company_id'), table_name='users_companies')
    op.drop_table('users_companies')
    # ### end Alembic commands ###
