"""remove profile_image_url from users

Revision ID: 31218685188a
Revises: bea6c147fb3c
Create Date: 2026-02-26 17:36:57.367460

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '31218685188a'
down_revision: str | Sequence[str] | None = 'bea6c147fb3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
