"""add companies table

Revision ID: 375042d7d902
Revises: b6ff38a53930
Create Date: 2026-03-02 19:03:00.690966

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '375042d7d902'
down_revision: str | Sequence[str] | None = 'b6ff38a53930'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mersis_number', sa.String(length=50), nullable=False),
    sa.Column('tax_number', sa.String(length=20), nullable=False),
    sa.Column('tax_office', sa.String(length=100), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # Company Profile Fields
    sa.Column('foundation_date', sa.Date(), nullable=True),
    sa.Column('headquarters_address', sa.String(length=500), nullable=True),
    # Financial Information
    sa.Column('iban_try', sa.String(length=34), nullable=True),
    # Activity Information
    sa.Column('nace_code', sa.String(length=20), nullable=True),
    sa.Column('activity_sector', sa.String(length=255), nullable=True),
    sa.Column('exporter_union', sa.String(length=255), nullable=True),
    sa.Column('hib_member_no', sa.String(length=100), nullable=True),
    # Contact Information
    sa.Column('contact_full_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('kep_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.create_index(op.f('ix_companies_mersis_number'), 'companies', ['mersis_number'], unique=False)
    op.create_index(op.f('ix_companies_tax_number'), 'companies', ['tax_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_tax_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_mersis_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
