"""update users table to new structure

Revision ID: 23fc1fe3f676
Revises: 3c7cfeb67e4f
Create Date: 2026-02-24 22:21:59.412501

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23fc1fe3f676'
down_revision: str | Sequence[str] | None = '3c7cfeb67e4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum = sa.Enum('user', 'admin', 'super_admin', name='user_role')
    user_role_enum.create(op.get_bind())

    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('role', user_role_enum, nullable=False))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_verified_at')
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum('user', 'admin', 'super_admin', name='user_role')
    user_role_enum.drop(op.get_bind())
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
