"""simplify company_brands and company_sector_profiles

Revision ID: 19ce1dd071b1
Revises: bc94816f00a3
Create Date: 2026-03-23 23:55:20.340464

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '19ce1dd071b1'
down_revision: str | Sequence[str] | None = 'bc94816f00a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['company_roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_invitations_company_id'), 'company_invitations', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_invitations_email'), 'company_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_company_invitations_id'), 'company_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_company_invitations_token'), 'company_invitations', ['token'], unique=True)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('freemium', 'basic', 'pro', 'premium', name='plan_tier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('extra_company_quota', sa.Integer(), nullable=False),
    sa.Column('extra_product_quota_per_company', sa.Integer(), nullable=False),
    sa.Column('extra_member_quota_per_company', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=True)
    op.add_column('company_brands', sa.Column('brand_url', sa.String(length=500), nullable=True))
    op.drop_column('company_brands', 'has_domestic_registration')
    op.drop_column('company_brands', 'has_international_registration')
    op.add_column('company_sector_profiles', sa.Column('data', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.drop_index(op.f('ix_company_sector_profiles_sector_type'), table_name='company_sector_profiles')
    op.drop_constraint(op.f('uq_company_sector_profile_field'), 'company_sector_profiles', type_='unique')
    op.drop_index(op.f('ix_company_sector_profiles_company_id'), table_name='company_sector_profiles')
    op.create_index(op.f('ix_company_sector_profiles_company_id'), 'company_sector_profiles', ['company_id'], unique=True)
    op.drop_column('company_sector_profiles', 'value_bool')
    op.drop_column('company_sector_profiles', 'value_text')
    op.drop_column('company_sector_profiles', 'value_json')
    op.drop_column('company_sector_profiles', 'value_date')
    op.drop_column('company_sector_profiles', 'value_numeric')
    op.drop_column('company_sector_profiles', 'field_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sector_profiles', sa.Column('field_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('company_sector_profiles', sa.Column('value_numeric', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('company_sector_profiles', sa.Column('value_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('company_sector_profiles', sa.Column('value_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('company_sector_profiles', sa.Column('value_text', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('company_sector_profiles', sa.Column('value_bool', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_company_sector_profiles_company_id'), table_name='company_sector_profiles')
    op.create_index(op.f('ix_company_sector_profiles_company_id'), 'company_sector_profiles', ['company_id'], unique=False)
    op.create_unique_constraint(op.f('uq_company_sector_profile_field'), 'company_sector_profiles', ['company_id', 'field_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_company_sector_profiles_sector_type'), 'company_sector_profiles', ['sector_type'], unique=False)
    op.drop_column('company_sector_profiles', 'data')
    op.add_column('company_brands', sa.Column('has_international_registration', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('company_brands', sa.Column('has_domestic_registration', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('company_brands', 'brand_url')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_company_invitations_token'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_id'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_email'), table_name='company_invitations')
    op.drop_index(op.f('ix_company_invitations_company_id'), table_name='company_invitations')
    op.drop_table('company_invitations')
    # ### end Alembic commands ###
