"""remove brand_name from company_sectors

Revision ID: f3722e52146e
Revises: 19ce1dd071b1
Create Date: 2026-03-24 11:15:15.130321

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f3722e52146e'
down_revision: str | Sequence[str] | None = '19ce1dd071b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_sectors', 'brand_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_sectors', sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
