# Company module configuration

DEFAULT_COMPANY_PAGE_SIZE = 10
MAX_COMPANY_PAGE_SIZE = 100

# Validation limits
MAX_COMPANY_NAME_LENGTH = 255
MAX_MERSIS_LENGTH = 50
MAX_TAX_NUMBER_LENGTH = 20
MAX_SEARCH_LENGTH = 100
