# Company module constants

COMPANY_OWNER_ROLE = "owner"
COMPANY_ADMIN_ROLE = "admin"
COMPANY_ACCOUNTANT_ROLE = "accountant"
COMPANY_VIEWER_ROLE = "viewer"

COMPANY_MANAGE_ROLES = {
    COMPANY_OWNER_ROLE,
    COMPANY_ADMIN_ROLE,
}

ALL_COMPANY_ROLES = {
    COMPANY_OWNER_ROLE,
    COMPANY_ADMIN_ROLE,
    COMPANY_ACCOUNTANT_ROLE,
    COMPANY_VIEWER_ROLE,
}
